### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by MuhammedKalkan** [ThatUsernameAlreadyExist/anyka-v4l2rtspserver#1]
Hello, Do you have instructions about how to.compile and run

There are issues with atomic definitions and anyka libs are not linked in make chain.
Also there is no instructions on compiler definition to cmake.

Thanks

**Comment by ThatUsernameAlreadyExist** [comment]
Hello, what specific errors does the compilation generate?
Here is a brief instruction:

All scripts for compilation located in this repository: https://github.com/ThatUsernameAlreadyExist/anyka-software.
1. Download it
2. The crosscompiler for Anyka is 32-bit (x86), so you need to enable support for 32-bit applications in your distro.  For example, on Ubuntu 22:
        
        sudo apt install libstdc++-i386
        sudo apt install lib32stdc++6
        sudo apt install libmpc-dev:i386
        sudo apt install libz1:i386
        sudo ln -s /lib/i386-linux-gnu/libmpfr.so.6 /lib/i386-linux-gnu/libmpfr.so.4 
        
        The last command makes a link to libmpfr.so, because the cross-compiler is linked to its old version 4, which is no longer present in modern distros.
3. After that you can compile v4l2rtspserver:
    - unzip the crosscompiler:
        ./crosscompiler.sh
    - build live555:
        ./live555.sh
    - install git (required by v4l2rtspserver)
        sudo apt install git
    - build v4l2rtspserver:
        ./v4l2rtspserver.sh
        
For manual compilation, you can view the contents of the v4l2rtspserver.sh script.
