### ISSUE TITLE
Compiled Binary

### ISSUE THREAD

**Issue by yawaweb** [ThatUsernameAlreadyExist/anyka-v4l2rtspserver#2]
Can you please upload the compiled binary file? I tried to compile it but unfortunately, I couldn't (I'm a beginner). I would be very grateful.

Here is some information about my camera:

Victure PC730
FW: 1.0.3

```
[root@anyka /]$ cat /proc/cpuinfo
Processor	: ARM926EJ-S rev 5 (v5l)
BogoMIPS	: 199.06
Features	: swp half fastmult edsp java 
CPU implementer	: 0x41
CPU architecture: 5TEJ
CPU variant	: 0x0
CPU part	: 0x926
CPU revision	: 5

Hardware	: CLOUD39EV3_AK3918EV300_MNBD
Revision	: 0000
Serial		: 0000000000000000
```

```
[root@anyka /]$ lsmod
Tainted: G  
8188fu 1320113 0 - Live 0xbf020000 (O)
otg_hs 18080 0 - Live 0xbf017000
sdio_wifi 1663 0 - Live 0xbf013000
ak_info_dump 1681 0 - Live 0xbf00f000
akcamera 16445 2 ak_info_dump, Live 0xbf005000
sensor_f22+f23+f28+f35+f37_mipi 5337 0 - Live 0xbf000000
```

**Comment by ThatUsernameAlreadyExist** [comment]
Compiled binary available here: https://github.com/ThatUsernameAlreadyExist/TECKIN-TC100-Anyka-AK3918-camera-hacks
v4l2rtspserver available in 'bin' directory, Libraries required for it are located in 'lib' dir. Config example - 'config/rtspserver.conf.dist'. How to run just v4l2rtspserver you can see in 'controlscripts/rtsp-h26x' script

**Comment by yawaweb** [comment]
Thank you very much! I use your library with micro SD i test it and it works perfect with Victure PC730

**Comment by yawaweb** [comment]
Thank you very much! I use your library with micro SD i test it and it works perfect with Victure PC730
